version: '2'
services:

    # Application container
    php:
        build: .
        restart: unless-stopped
        volumes:
            - ./:/server/http
        ports:
            - "8080:80"
            #- "443:443"
        links:
            - mysql
            - redis
        environment:
            DEBUG: 'true'

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_USER: hellofresh
            MYSQL_PASSWORD: hellofresh
            MYSQL_DB: hellofresh

    redis:
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        ports:
            - "6379:6379"
